# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/deep_learning',
                'doc_host': 'https://reutkeller.github.io',
                'git_url': 'https://github.com/reutkeller/deep_learning',
                'lib_path': 'deep_learning'},
  'syms': {'deep_learning.core': {'deep_learning.core.foo': ('core.html#foo', 'deep_learning/core.py')}}}
